# application configurations
spring.application.name=financial-data-processing

# DataSource Configuration
spring.datasource.url=<postgresql_db_url>
spring.datasource.username=<postgresql_db_username>
spring.datasource.password=<postgresql_db_password>
spring.jpa.hibernate.ddl-auto=<update, create-drop , create>
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
